version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: salonmanager_db_local
    environment:
      MYSQL_DATABASE: salonmanager
      MYSQL_USER: sm_admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7
    container_name: salonmanager_redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data:
  redis_data:
