version: '3.8'

services:
  app:
    build:
      context: ./salonmanager/backend
      dockerfile: Dockerfile
    container_name: salonmanager_app_prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./salonmanager/backend:/var/www/html
      - ./salonmanager/backend/storage:/var/www/html/storage
    networks:
      - salonmanager_network
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=salonmanager
      - DB_USERNAME=salonmanager
      - DB_PASSWORD=salonmanager_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis

  web:
    image: nginx:alpine
    container_name: salonmanager_web_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./salonmanager/backend/public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - salonmanager_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: salonmanager_db_prod
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=salonmanager
      - MYSQL_USER=salonmanager
      - MYSQL_PASSWORD=salonmanager_password
    networks:
      - salonmanager_network

  redis:
    image: redis:7-alpine
    container_name: salonmanager_redis_prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    networks:
      - salonmanager_network

  queue:
    build:
      context: ./salonmanager/backend
      dockerfile: Dockerfile
    container_name: salonmanager_queue_prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./salonmanager/backend:/var/www/html
      - ./salonmanager/backend/storage:/var/www/html/storage
    networks:
      - salonmanager_network
    depends_on:
      - db
      - redis
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=salonmanager
      - DB_USERNAME=salonmanager
      - DB_PASSWORD=salonmanager_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis

  scheduler:
    build:
      context: ./salonmanager/backend
      dockerfile: Dockerfile
    container_name: salonmanager_scheduler_prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./salonmanager/backend:/var/www/html
      - ./salonmanager/backend/storage:/var/www/html/storage
    networks:
      - salonmanager_network
    depends_on:
      - db
      - redis
    command: php artisan schedule:work
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=salonmanager
      - DB_USERNAME=salonmanager
      - DB_PASSWORD=salonmanager_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis

volumes:
  mysql_data_prod:
    driver: local
  redis_data_prod:
    driver: local

networks:
  salonmanager_network:
    driver: bridge
