name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (Laravel PHP 8.3)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer
      - name: Validate composer.json
        run: |
          if [ -f composer.json ]; then composer validate --no-check-lock; else echo "No composer.json yet (skeleton)"; fi
      - name: Install dependencies
        run: |
          if [ -f composer.json ]; then composer install --no-interaction --no-progress; else echo "Skip install (skeleton)"; fi
      - name: PHPStan
        run: |
          if [ -f ../ops/ci/linting/phpstan.neon ]; then vendor/bin/phpstan analyse -c ../ops/ci/linting/phpstan.neon || true; else echo "No PHPStan yet"; fi
      - name: Tests (Pest/PHPUnit)
        run: |
          if [ -d tests ]; then vendor/bin/pest || vendor/bin/phpunit || true; else echo "No tests yet"; fi

  frontend:
    name: Frontend (Flutter)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter pub get
        run: |
          if [ -f pubspec.yaml ]; then flutter pub get; else echo "No pubspec yet (skeleton)"; fi
      - name: Analyze
        run: |
          if [ -f pubspec.yaml ]; then flutter analyze || true; else echo "No project yet"; fi
      - name: Tests
        run: |
          if [ -f pubspec.yaml ]; then flutter test || true; else echo "No tests yet"; fi

  docs:
    name: Docs Lint (Markdown)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: |
            **/*.md
            !**/node_modules/**

